# Uncomment the next line to define a global platform for your project

platform :ios, '15.5'

target 'CodeComments' do
  
use_frameworks!

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'

# Facebook
pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
    
# Google Sign In
pod 'GoogleSignIn'

# Messaging
pod 'MessageKit'
pod 'JGProgressHUD'
pod 'SDWebImage'

# Calls
pod 'AgoraUIKit_iOS', '1.8.4'
pod 'AgoraRtcEngine_iOS', '3.7.0.3'
pod 'AgoraRtmControl_iOS', '1.8.4'

end
