# Uncomment the next line to define a global platform for your project

platform :ios, '16.1'

target 'CodeComments' do
  
use_frameworks!

# Firebase
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'FirebaseAnalytics', '8.1.0'
pod 'Firebase/Crashlytics'

# Sign In
pod 'GoogleSignIn', '5.0.2'
pod 'FBSDKLoginKit'

# Messaging
pod 'MessageKit'
pod 'JGProgressHUD'
pod 'SDWebImage'

# Calls
pod 'AgoraUIKit_iOS', '1.8.4'
pod 'AgoraRtcEngine_iOS', '3.7.0.3'
pod 'AgoraRtmControl_iOS', '1.8.4'

end
